<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta charset="utf-8">
<title>Issue 2008: Conflicting Error Conditions for packaged_task::operator()</title>
<style type="text/css">
  p {text-align:justify}
  li {text-align:justify}
  blockquote.note
  {
    background-color:#E0E0E0;
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 1px;
    padding-bottom: 1px;
  }
  ins {background-color:#A0FFA0}
  del {background-color:#FFA0A0}
  table {border-collapse: collapse;}
</style>
</head>
<body>
<hr>
<h3><a name="2008" href="2008">2008.</a> Conflicting Error Conditions for <tt>packaged_task::operator()</tt></h3>
<p><b>Section:</b> 30.6.9.1 <a href="https://timsong-cpp.github.io/cppwp/futures.task.members">[futures.task.members]</a> <b>Status:</b> <a href="lwg-active.html#C++11">C++11</a>
 <b>Submitter:</b> Pete Becker <b>Opened:</b> 2010-06-21 <b>Last modified:</b> 2016-01-28 10:01:27 UTC</p>
<p><b>Priority: </b>Not Prioritized
</p>
<p><b>View all other</b> <a href="lwg-index.html#futures.task.members">issues</a> in <a href="https://timsong-cpp.github.io/cppwp/futures.task.members">[futures.task.members]</a>.</p>
<p><b>View all issues with</b> <a href="lwg-status.html#C++11">C++11</a> status.</p>
<p><b>Discussion:</b></p>
<p>
The Throws clause for <tt>packaged_task::operator()</tt> says that it throws "a
<tt>future_error</tt> exception object if there is no associated asynchronous
state or the stored task has already been invoked." However, the Error
Conditions clause does not define an error condition when the stored task has
already been invoked, only when the associated state is already ready (i.e. the
invocation has completed).
</p>

<p><i>[2011-02-17 Anthony provides an alternative resolution]</i></p>


<p><strong>Previous</strong> proposed resolution:</p>

<p>
Change the first bullet item in 30.6.9.1 <a href="https://timsong-cpp.github.io/cppwp/futures.task.members">[futures.task.members]</a> /22:
</p>

<blockquote><pre>
void operator()(ArgTypes... args);
</pre>
<blockquote>
<p>
20 ...
</p>
<p>
21 ...
</p>
<p>
22 <i>Error conditions:</i>
</p>
<ul>
<li>
<tt>promise_already_satisfied</tt> if <del>the associated asynchronous state is
already ready</del> <ins><tt>operator()</tt> has already been called</ins>.
</li>
<li>
<tt>no_state</tt> if <tt>*this</tt> has no associated asynchronous state.
</li>
</ul>
</blockquote>
</blockquote>

<p><i>[Adopted at Madrid, 2011-03]</i></p>




<p><b>Proposed resolution:</b></p>
<ol>
<li>
<p>
Change the first bullet item in 30.6.9.1 <a href="https://timsong-cpp.github.io/cppwp/futures.task.members">[futures.task.members]</a> p. 17:
</p>

<blockquote><pre>
void operator()(ArgTypes... args);
</pre>
<blockquote>
<p>
15 ...
</p>
<p>
16 ...
</p>
<p>
17 <i>Error conditions:</i>
</p>
<ul>
<li>
<tt>promise_already_satisfied</tt> if the <del>associated asynchronous state is already 
ready</del><ins>stored task has already been invoked</ins>.
</li>
<li>
<tt>no_state</tt> if <tt>*this</tt> has no associated asynchronous state.
</li>
</ul>
</blockquote>
</blockquote>
</li>

<li>
<p>
Change the first bullet item in 30.6.9.1 <a href="https://timsong-cpp.github.io/cppwp/futures.task.members">[futures.task.members]</a> p. 21:
</p>

<blockquote><pre>
void make_ready_at_thread_exit(ArgTypes... args);
</pre>
<blockquote>
<p>
19 ...
</p>
<p>
20 ...
</p>
<p>
21 <i>Error conditions:</i>
</p>
<ul>
<li>
<tt>promise_already_satisfied</tt> if the <del>associated asynchronous state already has a stored value or
exception</del><ins>stored task has already been invoked</ins>.
</li>
<li>
<tt>no_state</tt> if <tt>*this</tt> has no associated asynchronous state.
</li>
</ul>
</blockquote>
</blockquote>

</li>
</ol>






</body>
</html>
