<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta charset="utf-8">
<title>Issue 3414: [networking.ts] service_already_exists has no usable constructors</title>
<style type="text/css">
  p {text-align:justify}
  li {text-align:justify}
  blockquote.note
  {
    background-color:#E0E0E0;
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 1px;
    padding-bottom: 1px;
  }
  ins {background-color:#A0FFA0}
  del {background-color:#FFA0A0}
  table {border-collapse: collapse;}
</style>
</head>
<body>
<hr>
<h3><a name="3414" href="lwg-defects.html#3414">3414.</a> [networking.ts] <tt>service_already_exists</tt> has no usable constructors</h3>
<p><b>Section:</b> 13.7 <a href="https://timsong-cpp.github.io/cppwp/networking-ts/async.exec.ctx">[networking.ts::async.exec.ctx]</a> <b>Status:</b> <a href="lwg-active.html#WP">WP</a>
 <b>Submitter:</b> Jonathan Wakely <b>Opened:</b> 2020-03-17 <b>Last modified:</b> 2020-11-09 20:41:54 UTC</p>
<p><b>Priority: </b>0
</p>
<p><b>View all issues with</b> <a href="lwg-status.html#WP">WP</a> status.</p>
<p><b>Discussion:</b></p>
<p><b>Addresses: networking.ts</b></p>
<p>
In the Networking TS, the <tt>service_already_exists</tt> exception type
has no constructors declared. The <tt>logic_error</tt> base class is not
default constructible, so <tt>service_already_exists</tt>'s implicit default
constructor is defined as deleted.
</p>
<p>
Implementations can add one or more private constructors that can be used
by <tt>make_service</tt>, but there seems to be little benefit to that.
The Boost.Asio type of the same name has a public default constructor.
</p>

<p><i>[2020-04-18 Issue Prioritization]</i></p>
 
<p>
Status set to Tentatively Ready after six positive votes on the reflector.
</p>
<p><i>[2020-11-09 Approved In November virtual meeting. Status changed: Tentatively Ready &rarr; WP.]</i></p>



<p><b>Proposed resolution:</b></p>
<p>
This wording is relative to <a href="https://wg21.link/n4734">N4734</a>.
</p>

<ol>
<li><p>Modify 13.7 <a href="https://timsong-cpp.github.io/cppwp/networking-ts/async.exec.ctx">[networking.ts::async.exec.ctx]</a> p1, as indicated:</p>

<blockquote>
<pre>
<i>// service access</i>
template&lt;class Service> typename Service::key_type&amp;
use_service(execution_context&amp; ctx);
template&lt;class Service, class... Args&gt; Service&amp;
make_service(execution_context&amp; ctx, Args&amp;&amp;... args);
template&lt;class Service&gt; bool has_service(const execution_context&amp; ctx) noexcept;
class service_already_exists : public logic_error <del>{ };</del>
<ins>{
public:
  service_already_exists();
};</ins>
</pre>
</blockquote>
</li>

<li>
<p>Add a new subclause after [async.exec.ctx.globals]:</p>

<blockquote>
<p>
<b>13.7.6 Class <tt>service_already_exists</tt> [async.exec.ctx.except]</b>
</p>

<p>
-1- The class <tt>service_already_exists</tt> defines the type of objects
thrown as exceptions to report an attempt to add an existing service
to an <tt>execution_context</tt>.
</p>
<pre>
service_already_exists();
</pre>
<blockquote>
<p>-2- <i>Postconditions:</i> <tt>what()</tt> returns an implementation-defined NTBS.</p>
</blockquote>
</blockquote>
</li>

</ol>




</body>
</html>
